name = "VulkanExamples"
uuid = "2b01c558-5549-4dee-872a-1b67e6308179"
authors = ["Cédric BELMANT"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
